#!/bin/bash
PATH="/home/zdjur/src/WL5460AP/gcc333/lexra-nnop-v5/bin/:$PATH"
#make clean
make
rm /home/zdjur/web/wive-ng/filesystem/tmp/web.tar.gz
cp webs /home/zdjur/web/wive-ng/filesystem/sbin
pushd /home/zdjur/web/wive-ng/filesystem/ >/dev/null
find ./web/ ! -iname "*~" ! -type d | xargs tar -czf ./tmp/web.tar.gz ./sbin/webs 
popd >/dev/null
echo Done